[package]
name = "compute-univ3-address"
version = "0.2.0"
edition = "2021"
authors = ["Yuichiro Aoki"]
description = "Compute Uniswap V3 address"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethers = "2.0.4"
